import 'Question_vocab.dart';

class VocabularyBank {
  int questionNumber = 0;
  List<Question> introQuestionBank = [
    Question(
        r'Latvia must ',
        r' implementing those equivocal immigration policies, which have created havoc among citizens.',
        r'lament',
        'A',
        null,
        r'condemn',
        r'mourn',
        r'revere',
        r'cherish'),
    Question(
      r'Mom and Dad used to ',
      r' about their youth over dinner, while I was contemplating running away to my toys.',
      r'reminisce',
      'C',
      null,
      r'express gratitude ',
      r'show disapproval ',
      r'recollect',
      r'admire',
    ),
    Question(r'Forgive my ', r' about my childhood.', r'musings', 'C', null,
        r'inspirations', r'representations', r'memories', r'inspirations'),
    Question(
      r'I ',
      r' on the most ambivalent event of my past.',
      r'reflect',
      'C',
      null,
      r'represent',
      r'recollect',
      r'think about',
      r'refute',
    ),
    Question(
      r'His mood swings went from being ',
      r' to excited in a matter of seconds.',
      r'apprehensive',
      'A',
      null,
      r'worried',
      r'dubious',
      r'sinister',
      r'malignant',
    ),
    Question(
      r'Students felt agitated because they didn’t know how to cope with their ',
      r' minds.',
      r'restless',
      'D',
      null,
      r'unable to stand still',
      r'unable to remember',
      r'disillusioned',
      r'constantly worried',
    ),
    Question(
      r'The president may not ',
      r' with the Senate.',
      r'concur',
      'A',
      null,
      r'agree',
      r'allow',
      r'enforce',
      r'lament',
    ),
    Question(
      r'He must ',
      r' that ...',
      r'concede',
      'C',
      null,
      r'muse',
      r'reminisce',
      r'admit',
      r'revere',
    ),
    Question(
      r'We can no longer ',
      r' age discrimination.',
      r'condone',
      'A',
      null,
      r'approve',
      r'agree',
      r'apprehend',
      r'denounce',
    ),
    Question(
      r'When we see disinformation ',
      r' through the ubiquitous Internet, we must warn the online users and encourage them to be apprehensive of the many news articles published on social media.',
      r'proliferate',
      'A',
      null,
      r'spread',
      r'agree',
      r'condone',
      r'condemn',
    ),
    Question(
      r'When we see disinformation proliferate through the ',
      r' Internet, we must warn the online users and encourage them to be apprehensive of the many news articles published on social media.',
      r'ubiquitous',
      'A',
      null,
      r'omnipresent',
      r'deferential',
      r'equivocal',
      r'malicious',
    ),
    Question(
      r'After having reminisced about their experiences for quite some time, they continued to write their ',
      r' memoir.',
      r'poignant',
      'D',
      null,
      r'enigmatic',
      r'ubiquitous',
      r'benevolent',
      r'sad',
    ),
    Question(
      r'Once her heart was broken, she became ',
      r', thinking she would never find love again.',
      r'despondent',
      'B',
      null,
      r'discontent',
      r'disheartened',
      r'endearing',
      r'sinister',
    ),
  ];

  int getLength() {
    return introQuestionBank.length;
  }

  void reset() {
    questionNumber = 0;
  }
}
