import 'Question_vocab.dart';

class VocabularyBank {
  int questionNumber = 0;
  List<Question> introQuestionBank = [
    Question(
        r'If they don’t allow the protest, it would be a ',
        r' of the First Amendment.',
        r'violation',
        'A',
        null,
        r'breach',
        r'authentication',
        r'hoax',
        r'endorsement'),
    Question(
      r'Jason decided to get rich and ',
      r' his family’s legacy of living on the brink of starvation from generation to generation.',
      r'defy',
      'B',
      null,
      r'to follow his family’s legacy',
      r'to go against his family’s legacy',
      r'to complain about his family’s legacy',
      r'to immortalize his family’s legacy',
    ),
    Question(
        r'Inviting Helen — a highly contentious person — to the party, will ',
        r' everyone’s experience.',
        r'mar',
        'B',
        null,
        r'leave a stain on',
        r'ruin',
        r'enhance',
        r'denounce'),
    Question(
      r'Lace bugs will discolor and ',
      r' the foliage, so farmers keep a close eye on them.',
      r'disfigure',
      'B',
      null,
      r'ruin the flavor of',
      r'spoil the appearance of',
      r'leave a small mark on',
      r'enhance the quality of',
    ),
    Question(
      r'The architect wanted to ensure that he used the ',
      r' road space of New York effectively.',
      r'finite',
      'C',
      null,
      r'expansive',
      r'perennial',
      r'limited',
      r'not working',
    ),
    Question(
      r'Despite her slight frame, she appeared ',
      r' in the face of difficulty.',
      r'tenacious',
      'C',
      null,
      r'courageous',
      r'poignant',
      r'unstoppable',
      r'brave',
    ),
    Question(
      r'No matter how bleak the circumstances look, an ',
      r' change is awaiting humanity if we persevere in our efforts.',
      r'inexorable',
      'A',
      null,
      r'unavoidable',
      r'questionable',
      r'ambivalent',
      r'earnest',
    ),
    Question(
      r'Bill could not have the evening go by without making a malicious remark to his old ',
      r'.',
      r'adversary',
      'A',
      null,
      r'antagonistic',
      r'poignant',
      r'amiable',
      r'dubious',
    ),
    Question(
      r'Cultivating him as an ',
      r' turned out to be the smartest thing to ensure the survival of their village during the war.',
      r'ally',
      'A',
      null,
      r'friend',
      r'antagonist',
      r'rival',
      r'perpetrator',
    ),
    Question(
      r'He always found ',
      r' his kids to be just as ineffective as cajoling and coaxing.',
      r'reproaching',
      'B',
      null,
      r'tricking',
      r'scolding',
      r'hating',
      r'ceasing',
    ),
    Question(
      r'As a father, he ',
      r' all parents to discuss the dangers of drinking with their kids.',
      r'implored',
      'A',
      null,
      r'urged',
      r'ordered',
      r'conceded',
      r'lamented',
    ),
    Question(
      r'His father’s stories always met the boy’s internal ',
      r' for adventure.',
      r'yearning',
      'B',
      null,
      r'passion',
      r'desire',
      r'ambition',
      r'ally',
    ),
    Question(
      r'It seemed like he could control the boy with his ',
      r'.',
      r'fervor',
      'B',
      null,
      r'desire',
      r'passion',
      r'decree',
      r'aspiration',
    ),
  ];

  int getLength() {
    return introQuestionBank.length;
  }

  void reset() {
    questionNumber = 0;
  }
}
