import 'Question_vocab.dart';

class VocabularyBank {
  int questionNumber = 0;
  List<Question> introQuestionBank = [
    Question(
        r'I hope you are not going to mistake my ',
        r' behavior toward your son for immaturity.',
        r'earnest',
        'D',
        null,
        r'sad',
        r'formal',
        r'grave',
        r'serious'),
    Question(
      r'They mourned in the ',
      r' memories of their grandfathers.',
      r'solemn',
      'D',
      null,
      r'intentional',
      r'formal',
      r'ceremonial',
      r'grave',
    ),
    Question(r'William stole a ', r' peek at Diana’s face.', r'deferential',
        'D', null, r'irreverent', r'solemn', r'earnest', r'respectful'),
    Question(
      r'He ',
      r' her father and didn’t want to upset him.',
      r'revered',
      'B',
      null,
      r'feared',
      r'respected',
      r'disregarded',
      r'refuted',
    ),
    Question(
      r'',
      r' citizens in Kursk had been sympathetic to our plight.',
      r'Benevolent',
      'B',
      null,
      r'good looking',
      r'charitable',
      r'charming',
      r'charitable',
    ),
    Question(
      r'The sentiment was very ',
      r'.',
      r'endearing',
      'B',
      null,
      r'charitable',
      r'sweet',
      r'genius',
      r'selfish',
    ),
    Question(
      r'The problem was much bigger than a few ',
      r' financial operations.',
      r'malicious',
      'B',
      null,
      r'unsound',
      r'sinister',
      r'beneficial',
      r'endearing',
    ),
    Question(
      r'He appreciated her ',
      r' words. It was invaluable to talk to someone who could relate to his struggles.',
      r'candid',
      'C',
      null,
      r'kind',
      r'earnest',
      r'frank',
      r'respectful',
    ),
    Question(
      r'The singer’s last song was the most ',
      r' and poignant moment of the show.',
      r'authentic',
      'A',
      null,
      r'not fake',
      r'creative',
      r'sad',
      r'pure',
    ),
    Question(
      r'Whether that’s an authentic story or an elaborate ',
      r', Stephen knows how to put on a great show.',
      r'hoax',
      'A',
      null,
      r'fabrication',
      r'virtue',
      r'malice',
      r'trick',
    ),
    Question(
      r'He was intentionally ',
      r' in his answers to the journalists.',
      r'ambiguous',
      'B',
      null,
      r'undecided',
      r'vague',
      r'biased',
      r'malevolent',
    ),
    Question(
      r'He was still ',
      r' about becoming mayor of the city.',
      r'ambivalent',
      'B',
      null,
      r'obscure',
      r'undecided',
      r'enigmatic',
      r'sinister',
    ),
    Question(
      r'Despite the unequivocal desire to conquer the North Pole, its underpinnings remained ',
      r' to him.',
      r'enigmatic',
      'B',
      null,
      r'ambiguous',
      r'uncertain',
      r'clear',
      r'magical',
    ),
  ];

  int getLength() {
    return introQuestionBank.length;
  }

  void reset() {
    questionNumber = 0;
  }
}
