import 'Question_writing.dart';

class WritingBank {
  int questionNumber = 0;
  List<Question> introQuestionBank = [
    Question(
      r'Before our conversation yesterday, Paul ',
      r' the word "brouhaha." Now he hears it everywhere he goes.',
      r'has never heard',
      'B',
      null,
      r'NO CHANGE',
      r'had never heard',
      r'was never heard by',
      r'was never hearing',
    ),
    Question(
      r'Ellen DeGeneres, who had her first major debut in 1986, recently ',
      r' a new lifestyle brand.',
      r'was launching',
      'B',
      null,
      r'NO CHANGE',
      r'launched',
      r'was launched by',
      r'is launching',
    ),
    Question(
      r'Despite being raised in a time and place in which black students were prevented or discouraged from attaining higher education, Percy Julian went on to become a PhD and a successful chemist. His most famous invention ',
      r' Aero-Foam, a soy protein fire extinguisher used in World War II.',
      r'were',
      'B',
      null,
      r'NO CHANGE',
      r'was',
      r'would be',
      r'was by',
    ),
    Question(
      r'The Whitney Footbridge in Minneapolis ',
      r' an engraving of a John Ashbery poem; pedestrians can read the poem as they walk.',
      r'features',
      'A',
      null,
      r'NO CHANGE',
      r'was featuring',
      r'was featured by',
      r'would be featuring',
    ),
    Question(
      r'It is a surprise that the American rapper Vanilla Ice ',
      r' a personal ice cream brand.',
      r'was not owning',
      'B',
      null,
      r'NO CHANGE',
      r'does not own',
      r'is not owned by',
      r'is not owning',
    ),
    Question(
      r'Once Christopher wrestled Fluffers into his Halloween costume, the cat ',
      r' limp and refused to move.',
      r'goes',
      'C',
      null,
      r'NO CHANGE',
      r'has gone',
      r'went',
      r'was going',
    ),
    Question(
      r'After the explorer Hernán Cortés arrived in South America, he ',
      r' all his ships, preventing his crew from returning home.',
      r'is setting fire to',
      'C',
      null,
      r'NO CHANGE',
      r'has set fire to',
      r'set fire to',
      r'was set on fire by',
    ),
    Question(
      'The world\'s most highly successful people carefully preserve their restorative habits, such as ',
      r' physical activity, making time for hobbies, and practicing stillness.',
      r'to get',
      'B',
      null,
      r'NO CHANGE',
      r'getting',
      r'having gotten',
      r'gets',
    ),
    Question(
      r'Benjamin Franklin ',
      ' the proverb "Early to bed, early to rise makes a man healthy, wealthy, and wise" in the 1735 edition of Poor Richard\'s Almanack.',
      r'is publishing',
      'B',
      null,
      r'NO CHANGE',
      r'published',
      r'has published',
      r'was published by',
    ),
    Question(
      r'The pink plastic lawn flamingo ',
      r' in 1957 by Don Featherstone.',
      r'is inventing',
      'B',
      null,
      r'NO CHANGE',
      r'was invented',
      r'which will be invented',
      r'having invented',
    ),
    Question(
      'Tabitha\'s eyes widened: the vanilla ice cream ',
      r' in a sea of hot fudge like a small rubber duck in the middle of the ocean.',
      r'was floating',
      'A',
      null,
      r'NO CHANGE',
      r'will float',
      r'is floating',
      r'floats',
    ),
    Question(
      r'Pedicabs, which are becoming increasingly popular in US cities, go by different names all over the world. For example, the Malagasy people of Madagascar ',
      r' the pedicab a "pousse-pousse," while Bangladeshis use the term "rickshaw."',
      r'are calling',
      'C',
      null,
      r'NO CHANGE',
      r'should have called',
      r'call',
      r'are called by',
    ),
    Question(
      r'If I get a Venus flytrap, it ',
      r' my pet fly, Herman.',
      r'ate',
      'C',
      null,
      r'NO CHANGE',
      r'will be eating',
      r'might eat',
      r'eats',
    ),
  ];

  int getLength() {
    return introQuestionBank.length;
  }

  void reset() {
    questionNumber = 0;
  }
}
