import 'Question_writing.dart';

class WritingBank {
  int questionNumber = 0;
  List<Question> introQuestionBank = [
    Question(
      r'The rescue team members wondered if they should call for backup or try to attempt the rescue ',
      r'',
      r'themselves?',
      'B',
      null,
      r'NO CHANGE',
      r'themselves.',
      r'themselves!',
      r'themselves,',
    ),
    Question(
      r'Watch ',
      r' bird is headed straight for your head!',
      r'out? That',
      'D',
      null,
      r'NO CHANGE',
      r'out. That',
      r'out that',
      r'out! That',
    ),
    Question(
      r"It's not a question of if my three best friends will see the new Star Wars movie, but ",
      r'',
      r'when.',
      'A',
      null,
      r'NO CHANGE',
      r'when,',
      r'when;',
      r'when —',
    ),
    Question(
      r'The oddest protester at the waterfront redevelopment rally was a large foam ',
      r'',
      r'duck.',
      'A',
      null,
      r'NO CHANGE',
      r'duck?',
      r'duck...',
      r'duck —',
    ),
    Question(
      r'Does anyone know the difference between ',
      r'',
      r'regular, and fancy ketchup?',
      'B',
      null,
      r'NO CHANGE',
      r'regular and fancy ketchup?',
      r'regular and fancy ketchup.',
      r'regular, and fancy ketchup.',
    ),
    Question(
      r'“Does pointillism use dots—or was it lines?” the weary art student wondered aloud, before falling ',
      r'',
      r'asleep?',
      'B',
      null,
      r'NO CHANGE',
      r'asleep.',
      r'asleep;',
      r'asleep —',
    ),
    Question(
      r'Fundamentally, we know that light is both a particle and a wave. We also know that light travels extraordinarily ',
      r'',
      r'fast!',
      'A',
      null,
      r'NO CHANGE',
      r'fast;',
      r'fast —',
      r'fast...',
    ),
    Question(
      r'"',
      ' I\'m late for work!" Emily called fruitlessly after the departing bus.',
      r'Stop.',
      'B',
      null,
      r'NO CHANGE',
      r'Stop!',
      r'Stop?',
      r'Stop',
    ),
    Question(
      r'In his 1532 book of political theory, The Prince, Niccolò Machiavelli poses the question of whether it is better to be loved or ',
      r'',
      r'feared?',
      'C',
      null,
      r'NO CHANGE',
      r'feared —',
      r'feared.',
      r'feared...',
    ),
    Question(
      r'Be ',
      r' hurricane is expected to arrive any minute now!',
      r'careful! The',
      'A',
      null,
      r'NO CHANGE',
      r'careful the',
      r'careful. The',
      r'careful? The',
    ),
    Question(
      r'It was not clear from his facial expression whether he preferred the salmon sushi or the shrimp ',
      r' possible that he liked them both equally.',
      r'roll? It’s',
      'B',
      null,
      r'NO CHANGE',
      r"roll. It's",
      r'roll? Its',
      r'roll. Its',
    ),
    Question(
      r'James vacillated between applying to medical school and taking a year to do ',
      r'',
      r'laboratory research?',
      'B',
      null,
      r'NO CHANGE',
      r'laboratory research.',
      r'laboratory research!',
      r'laboratory, research?',
    ),
    Question(
      '"It looks like it\'s going to ',
      r' Do you think I should bring my umbrella?" Antonio asked his father.',
      r'rain?',
      'D',
      null,
      r'NO CHANGE',
      r'rain',
      r'rain,',
      r'rain.',
    ),
  ];

  int getLength() {
    return introQuestionBank.length;
  }

  void reset() {
    questionNumber = 0;
  }
}
