import 'Question_writing.dart';

class WritingBank {
  int questionNumber = 0;
  List<Question> introQuestionBank = [
    Question(
      r'Solar charging kiosks are gaining popularity among entrepreneurs in Rwanda, where a sunny ',
      r' periodic power outages, and busy executives have increased the demand for solar energy.',
      r'climate,',
      'A',
      null,
      r'NO CHANGE',
      r'climate',
      r'climate:',
      r'climate;',
    ),
    Question(
      r'New evidence suggests that children are more likely to confide in their pets than their siblings when faced with difficult circumstances like ',
      r' or divorce.',
      r'grief; illness;',
      'C',
      null,
      r'NO CHANGE',
      r'grief illness',
      r'grief, illness,',
      r'grief: illness:',
    ),
    Question(
      r"There were only three things that Jonathan's toddler would eat: ",
      r' chocolate chips, and fried green tomatoes.',
      r'crackers',
      'C',
      null,
      r'NO CHANGE',
      r'crackers:',
      r'crackers,',
      r'crackers;',
    ),
    Question(
      r'Money-wasting practices include cooking too much ',
      r' throwing out leftovers, and storing food incorrectly.',
      r'food',
      'C',
      null,
      r'NO CHANGE',
      r'food:',
      r'food,',
      r'food;',
    ),
    Question(
      r'Chi-Ray sampled lemon-infused olive ',
      r' truffle-flavored vinegar, and a tea made from flowers.',
      r'oil,',
      'A',
      null,
      r'NO CHANGE',
      r'oil',
      r'oil;',
      r'oil:',
    ),
    Question(
      r'Malayan tapirs are ',
      r' herbivorous, and crepuscular.',
      r'solitary:',
      'B',
      null,
      r'NO CHANGE',
      r'solitary,',
      r'solitary',
      r'solitary;',
    ),
    Question(
      r'When it comes to personal fitness devices, people either love ',
      r' worry about their data collection, or doubt their accuracy.',
      r'them',
      'B',
      null,
      r'NO CHANGE',
      r'them,',
      r'them;',
      r'them:',
    ),
    Question(
      r'In order to compete for employees, companies are offering incentives like free ',
      r' opportunities to work from home, and paid parental leave.',
      r'childcare;',
      'C',
      null,
      r'NO CHANGE',
      r'childcare',
      r'childcare,',
      r'childcare:',
    ),
    Question(
      r'Ryan Reynolds has starred in films as diverse as Green ',
      r' The Proposal, and Turbo.',
      r'Lantern,',
      'A',
      null,
      r'NO CHANGE',
      r'Lantern;',
      r'Lantern',
      r'Lantern:',
    ),
    Question(
      r'The sandpipers were very active: they skittered along the ',
      r' pecked at dead bugs, and avoided sand-trampling tourists.',
      r'beach',
      'D',
      null,
      r'NO CHANGE',
      r'beach;',
      r'beach:',
      r'beach,',
    ),
    Question(
      r'Rosemary was known for her witty personality: she peppered her comments with verbal ',
      r' was able to time her retorts to perfection, and could mint a new joke for any occasion.',
      r'puns',
      'D',
      null,
      r'NO CHANGE',
      r'puns;',
      r'puns –',
      r'puns,',
    ),
    Question(
      r'Tennis athletes often eat pasta the night before the ',
      r' a Superbar during the match, and a salad after the match.',
      r'match:',
      'B',
      null,
      r'NO CHANGE',
      r'match,',
      r'match;',
      r'match –',
    ),
    Question(
      r"Titan, one of Saturn’s moons, has several Earth-like features, including ",
      r' rivers, and polar winds.',
      r'rainfall,',
      'A',
      null,
      r'NO CHANGE',
      r'rainfall',
      r'rainfall;',
      r'rainfall:',
    ),
  ];

  int getLength() {
    return introQuestionBank.length;
  }

  void reset() {
    questionNumber = 0;
  }
}
