import 'Question_writing.dart';

class WritingBank {
  int questionNumber = 0;
  List<Question> introQuestionBank = [
    Question(
      r'Although we know the fourth planet from the sun as "Mars" today, ',
      r' it has had many names from many different cultures.',
      r'because',
      'D',
      null,
      r'NO CHANGE',
      r'after',
      r'given that',
      r'Delete the underlined portion',
    ),
    Question(
      r'Franklin struggled with French pronunciation, ',
      r' his professor suggested that he watch French movies to become more familiar with the sound of the language.',
      r'so',
      'A',
      null,
      r'NO CHANGE',
      r'because',
      r'yet',
      r'or',
    ),
    Question(
      r'Some scientists propose that thumb sucking in children is a habit which is developed at birth, ',
      r' a recent theory suggests that it is neurologically and genetically based.',
      r'and',
      'С',
      null,
      r'NO CHANGE',
      r'considering that',
      r'but',
      r'since',
    ),
    Question(
      r'As the hot air balloon got close to the surface of the lake, Ginger jumped and landed in the water ',
      r' she could not take one more terrible joke from the pilot.',
      r'and',
      'D',
      null,
      r'NO CHANGE',
      r'but',
      r'even though',
      r'because',
    ),
    Question(
      r'When surfing, I don’t wear shiny jewelry or bright colors ',
      r' I don’t attract sharks.',
      r'since',
      'B',
      null,
      r'NO CHANGE',
      r'so that',
      r'and',
      r'because',
    ),
    Question(
      'As a cat lover, Hadley visited Japan to explore the country\'s "cat islands," ',
      r' cats outnumber human residents six to one.',
      r'where',
      'A',
      null,
      r'NO CHANGE',
      r'although',
      r'but',
      r'nevertheless',
    ),
    Question(
      r'Justine refuses to continue the family legacy of bull-riding ',
      r' the rodeo judges permit her to ride the same-sized bull that her father rode.',
      r'unless',
      'A',
      null,
      r'NO CHANGE',
      r'and',
      r'provided that',
      r'instead',
    ),
    Question(
      r'In 1892, Americans wanted a public structure to rival the Eiffel Tower, ',
      r' an engineer named George Ferris designed the Ferris wheel.',
      r'for',
      'C',
      null,
      r'NO CHANGE',
      r'although',
      r'so',
      r'or',
    ),
    Question(
      r'Andre and Chuck played chess together ',
      r' after fifteen years, Andre had only won once.',
      r'every day, but',
      'A',
      null,
      r'NO CHANGE',
      r'every day, since',
      r'every day,',
      r'every day, for',
    ),
    Question(
      r'',
      r' the Declaration of Independence was approved on July 4 of 1776, it was not actually signed until August 2.',
      r'Before',
      'D',
      null,
      r'NO CHANGE',
      r'Given that',
      r'Becauses',
      r'Although',
    ),
    Question(
      r'',
      r' it may not be the longest in history, one 2010 traffic jam near Beijing, China lasted for 12 days and spanned 62 miles.',
      r'Whereas',
      'D',
      null,
      r'NO CHANGE',
      r'Considering',
      r'But',
      r'Although',
    ),
    Question(
      r'A collection of exiled Puritans, merchants, and fortune-seekers signed a document they called the Mayflower Compact on November 11, 1620, ',
      r' by doing so they announced their intent to settle what is now southeastern Massachusetts.',
      r'or',
      'B',
      null,
      r'NO CHANGE',
      r'and',
      r'yet',
      r'but',
    ),
    Question(
      r'Yasir wanted to attend the lock-in laser tag party hosted by his school, ',
      r' his parents did not think it would be a good idea.',
      r'furthermore,',
      'B',
      null,
      r'NO CHANGE',
      r'but',
      r'additionally,',
      r'moreover,',
    ),
  ];

  int getLength() {
    return introQuestionBank.length;
  }

  void reset() {
    questionNumber = 0;
  }
}
