import 'Question_writing.dart';

class WritingBank {
  int questionNumber = 0;
  List<Question> introQuestionBank = [
    Question(
      r'Motorcyclists should inspect their helmets and check the motorcycle’s tires before ',
      r'.',
      r'you ride',
      'D',
      null,
      r'NO CHANGE',
      r'he rides',
      r'it rides',
      r'they ride',
    ),
    Question(
      r'When the professor introduced himself on the first day, Molly and Harriet realized with embarrassment that he was speaking Spanish and that ',
      r' in the wrong class.',
      r'she was',
      'C',
      null,
      r'NO CHANGE',
      r"Harriett's",
      r'they were',
      r'DELETE the bolded portion',
    ),
    Question(
      r'A career in engineering can be very exciting. You may not enjoy the many hours of working on fine details, but ',
      r' the satisfaction of seeing your bridge constructed.',
      r'it gets',
      'B',
      null,
      r'NO CHANGE',
      r'you get',
      r"it's",
      r'they get',
    ),
    Question(
      r'At a public school called Quest to Learn in New York, teachers use ',
      r' to teach because students love playing them.',
      r'video games',
      'A',
      null,
      r'NO CHANGE',
      r'a video game',
      r'an electronic game',
      r'DELETE the bolded portion',
    ),
    Question(
      r'Before you cross the street, ',
      r' should always look both ways.',
      r'one',
      'B',
      null,
      r'NO CHANGE',
      r'you',
      r'he or she',
      r'they',
    ),
    Question(
      r'Although robots will one day help with household chores, ',
      r' will never completely replace human cleaners.',
      r'it',
      'B',
      null,
      r'NO CHANGE',
      r'they',
      r'he',
      r'you',
    ),
    Question(
      r'One should obtain all necessary vaccinations before ',
      r' brings home a dog.',
      r'one',
      'A',
      null,
      r'NO CHANGE',
      r'them',
      r'you',
      r'it',
    ),
    Question(
      r'As the children sang along to the old songs of the Sound of Music, ',
      r' began to feel happy.',
      r'they',
      'A',
      null,
      r'NO CHANGE',
      r'he',
      r'you',
      r'it',
    ),
    Question(
      r'For a boat to move forward, ',
      r' must have enough force to push its own weight in water out of the way.',
      r'you',
      'B',
      null,
      r'NO CHANGE',
      r'it',
      r'we',
      r'they',
    ),
    Question(
      r'Happiness is a state of mind we all strive to achieve; however, ',
      r' sometimes difficult to obtain.',
      r'it is',
      'A',
      null,
      r'NO CHANGE',
      r'he is',
      r'you are',
      r'they are',
    ),
    Question(
      r'When tourists visit the Las Vegas Strip, ',
      r' will find Paris, Venice, pirates and a volcano—all within a four-mile stretch!',
      r'you',
      'D',
      null,
      r'NO CHANGE',
      r'yours',
      r'we',
      r'they',
    ),
    Question(
      'An Actor Prepares, Building a Character, and Creating a Role describe Constantin Stanislavski\'s "System" of acting. ',
      r' among the most read books on the craft.',
      r'Some are',
      'C',
      null,
      r'NO CHANGE',
      r'It is',
      r'They are',
      r'Ours are',
    ),
    Question(
      r'Although MeetMe has become the most popular social media site, ',
      r' still competes with Friendspace, YouPic, and Snapzone for user time.',
      r'it',
      'A',
      null,
      r'NO CHANGE',
      r'they',
      r'he',
      r'you',
    ),
  ];

  int getLength() {
    return introQuestionBank.length;
  }

  void reset() {
    questionNumber = 0;
  }
}
