import 'Question_writing.dart';

class WritingBank {
  int questionNumber = 0;
  List<Question> introQuestionBank = [
    Question(
      r'Although the black diamond ski run was clearly marked, Simon ',
      r' he thought it was a less-challenging green circle trail.',
      r'insisted which',
      'B',
      null,
      r'NO CHANGE',
      r'insisted that',
      r'insisting',
      r'insisted in',
    ),
    Question(
      r'The environmentalist spoke to the audience about plant-based meat as an alternative ',
      r' conventionally-raised meat, describing the ways that processed plant proteins and heme molecules could mimic a hamburger.',
      r'with',
      'D',
      null,
      r'NO CHANGE',
      r'on',
      r'under',
      r'to',
    ),
    Question(
      r'The messy toolbox was filled with a variety ',
      r' ratchets and hex wrenches, making it difficult to know which one was needed for a given job.',
      r'to',
      'B',
      null,
      r'NO CHANGE',
      r'of',
      r'as',
      r'through',
    ),
    Question(
      r'Despite having only had a few minutes to study the information packet before being rushed onstage, the young debater showed a powerful command ',
      r' the facts.',
      r'on',
      'C',
      null,
      r'NO CHANGE',
      r'from',
      r'of',
      r'over',
    ),
    Question(
      r'Before his arrest, the mayor was a notorious proponent ',
      r' land deals that always seemed to benefit companies owned by his friends.',
      r'of',
      'A',
      null,
      r'NO CHANGE',
      r'by',
      r'to',
      r'at',
    ),
    Question(
      r'James, the new medical resident, was ',
      r' awe of the other older doctors in the hospital; he envied their expertise.',
      r'in',
      'A',
      null,
      r'NO CHANGE',
      r'under',
      r'on',
      r'across',
    ),
    Question(
      r'The executive was adept ',
      ' improvisation; she was so talented that most people assumed she\'d written and rehearsed her speeches beforehand.',
      r'for',
      'D',
      null,
      r'NO CHANGE',
      r'by',
      r'to',
      r'at',
    ),
    Question(
      r'The judges were impressed ',
      ' Bettina\'s audacious pie, which contained six kinds of fruit and a complex lattice top.',
      r'of',
      'C',
      null,
      r'NO CHANGE',
      r'at',
      r'by',
      r'into',
    ),
    Question(
      r'At the start of the bout, the boxing referee listed all the illegal maneuvers and behaviors that he expected the combatants to refrain ',
      r' performing.',
      r'from',
      'A',
      null,
      r'NO CHANGE',
      r'over',
      r'to',
      r'by',
    ),
    Question(
      r'Before cleaning the indoor snake enclosures at the Cincinnati Zoo, workers first must check to make certain that the rooms are, in fact, devoid ',
      r' snakes.',
      r'with',
      'D',
      null,
      r'NO CHANGE',
      r'to',
      r'on',
      r'of',
    ),
    Question(
      r'During the Cold War, many Americans lived in fear that the country would have to resort ',
      r' nuclear combat with Russia.',
      r'with',
      'C',
      null,
      r'NO CHANGE',
      r'for',
      r'to',
      r'over',
    ),
    Question(
      r'"You can be a real pain ',
      ' the neck," said the man, cleaning up his dog\'s mess.',
      r'about',
      'D',
      null,
      r'NO CHANGE',
      r'of',
      r'by',
      r'in',
    ),
    Question(
      r'A Japanese electronics company has invented a new type of rubber that generates electricity ',
      r' stretched.',
      r'in',
      'B',
      null,
      r'NO CHANGE',
      r'when',
      r'over',
      r'under',
    ),
  ];

  int getLength() {
    return introQuestionBank.length;
  }

  void reset() {
    questionNumber = 0;
  }
}
