import 'Question_writing.dart';

class WritingBank {
  int questionNumber = 0;
  List<Question> introQuestionBank = [
    Question(
      r"More than half a decade after the magnitude 7.0 earthquake that leveled Haiti, serious social and public health problems ",
      r', including inadequate housing, political corruption, and the spread of cholera.',
      r'tolerate',
      'C',
      null,
      r'NO CHANGE',
      r'pursue',
      r'persist',
      r'keep going',
    ),
    Question(
      r"Some residents were surprised by how Senator Nikita Kapoor voted on the tax bill, but she argued that her intentions had been ",
      r' from the beginning of her campaign.',
      r'crystalline',
      'B',
      null,
      r'NO CHANGE',
      r'clear',
      r'limpid',
      r'sheer',
    ),
    Question(
      r"Voltaire was both disappointed and excited when he found out that his favorite coffee shop, Candid Coffee, was moving to a new and larger ",
      r'.',
      r'point',
      'C',
      null,
      r'NO CHANGE',
      r'position',
      r'location',
      r'orientation',
    ),
    Question(
      r"Sahil believed in the importance of excellent customer service, but it was ",
      r' to remain professional when the customer ordered a fruit smoothie, complained that it tasted like fruit, and then dumped the drink on the floor when she was denied a refund.',
      r'a challenge',
      'A',
      null,
      r'NO CHANGE',
      r'an impediment',
      r'an obstruction',
      r'an opposition',
    ),
    Question(
      r'Numerous research projects, including the benchmark Framingham Heart Study, demonstrate that taking a vacation can have ',
      r' health benefits.',
      r'well-connected',
      'B',
      null,
      r'NO CHANGE',
      r'valuable',
      r'prestigious',
      r'weighty',
    ),
    Question(
      r'In her historic 1963 book, The Feminine Mystique, Betty Friedan identified "The Problem That Has No Name"—the psychological ',
      r' for women who wanted to pursue professions but (due to the cultural restrictions of that era) were destined to be homemakers.',
      r'scuffle',
      'C',
      null,
      r'NO CHANGE',
      r'melee',
      r'struggle',
      r'bout',
    ),
    Question(
      r'Located on the northern coast of South America, Suriname ',
      r' the most untouched rainforest on the continent.',
      r'perpetuates',
      'C',
      null,
      r'NO CHANGE',
      r'stores',
      r'preserves',
      r'stashes',
    ),
    Question(
      r'All Molly wanted to do was ',
      r' a direct route to the beach, but her GPS kept losing its signal.',
      r'navigate',
      'A',
      null,
      r'NO CHANGE',
      r'convey',
      r'voyage',
      r'maneuver',
    ),
    Question(
      r'When she moved to a new town, Cecilia joined a book club to ',
      r' friendships with people who shared her interests.',
      r'harvest',
      'B',
      null,
      r'NO CHANGE',
      r'cultivate',
      r'tend',
      r'burgeon',
    ),
    Question(
      r'Before the Black Plague hit Europe in the 14th century, medieval people did not bathe by ',
      r' themselves in a tub of water, which they considered an act of debauchery. Instead they quickly cleaned themselves with water and a cloth.',
      r'submerging',
      'A',
      null,
      r'NO CHANGE',
      r'drowning',
      r'engulfing',
      r'sheathing',
    ),
    Question(
      r'In a recent study, Scientific American magazine concluded that dog owners are somewhat less reserved than cat owners, enjoying more social interaction and ',
      r' activity.',
      r'communal',
      'A',
      null,
      r'NO CHANGE',
      r'congruous',
      r'conjoined',
      r'coincident',
    ),
    Question(
      r'From a ',
      r' age, Frederica was destined for a career in theater; her mannerisms and way of speaking had always been excessively dramatic.',
      r'young',
      'A',
      null,
      r'NO CHANGE',
      r'naive',
      r'undeveloped',
      r'callow',
    ),
    Question(
      r'Julie believes that a ',
      r' bedroom is the mark of an organized person. So when she interviews potential new employees, she asks them to describe their living space.',
      r'pure',
      'A',
      null,
      r'NO CHANGE',
      r'spotless',
      r'stainless',
      r'antiseptic',
    ),
    // Question(
    //   r'',
    //   r'',
    //   r'',
    //   'A',
    //   null,
    //   r'NO CHANGE',
    //   r'',
    //   r'',
    //   r'',
    // ),
  ];

  int getLength() {
    return introQuestionBank.length;
  }

  void reset() {
    questionNumber = 0;
  }
}
